# Generated by Django 4.2.9 on 2024-01-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="aouthor",
            new_name="author",
        ),
    ]
